feat(parser): extract authors from CFF files
SDSC-ORD/gimie pull request #115
Opened 2024-11-18 16:23 UTC by rmfranken

This branch makes it possible to retrieve "author" objects from a CFF file and write them to turtle. It slightly refactored the generic parse function to output a graph structure (triples) instead of properties and values ("doubles?").

Additionally, minor fixes in poetry dependencies.

2024-11-18 16:28 UTC, rmfranken commented
@cmdoret I'm especially interested in the tests - how do you generally decide how "deep" to test? Looking at the other tests I saw the level detail was not super high, so I tried to match that in my test- but happy to hear if there is a better way of deciding that.

Also, I think the container registry action that is failing seems to be related to a version number? Is that something I should add to my PR somehow? It seems related to the version of git, rather than any code I added :/

2024-11-19 10:54 UTC, cmdoret commented on gimie/parsers/__init__.py
> +from rdflib import Graph, URIRef
```suggestion
from rdflib import Graph
```

fix: unused import

2024-11-19 17:09 UTC, cmdoret requested changes
Nice work! I have a bunch of suggestions to improve code readability.

About tests: I would just add a test for behaviour on a cff with broken orcid (not a uri) and authors without doi. And making sure they don't appear in the output.

2024-11-20 09:32 UTC, rmfranken commented on gimie/parsers/cff.py
> +                    (self.subject, SDO.author, URIRef(author["orcid"]))
assigning once I like, but the URIRef I think still makes sense to do at the .add step, as I will need it as a string in one case, and as a URIRef in the other.

2024-11-20 10:48 UTC, rmfranken commented on tests/test_output.py
> +# @pytest.mark.skip("not yet implemented")
fixed by yeeting pyshacl out completely

2024-11-22 10:15 UTC, rmfranken commented
Since I was making a orcid matcher, I thought I would also move the doi matching logic to utils. Does that make sense?

2024-11-27 15:14 UTC, cmdoret reviewed
Nice, this is starting to look really good! I have a few suggestions to improve things but most of them are optional.

The only really important one is the orcid url check in CffParser.

2024-11-27 15:14 UTC, cmdoret commented on tests/test_cff.py
> +    )
```suggestion
    assert len(
        CffParser(subject=URIRef("https://example.org/"))
        .parse(data=cff_file_emptyish)
        ) == 0
    
    assert len(
        CffParser(subject=URIRef("https://example.org/"))
        .parse(data=cff_file_bad_syntax)
    ) == 0
    
    assert len(
        CffParser(subject=URIRef("https://example.org/"))
        .parse(data=cff_file_broken_orcid)
    ) == 0
    
    assert len(
        CffParser(subject=URIRef("https://example.org/"))
        .parse(data=cff_file_author_without_orcid)
    ) == 0
```
**comment:** relying on serialization conventions is kinda brittle (they can change the newline thing).
**suggestion:** actually test expectation on the graph structure itself

2024-11-27 15:14 UTC, cmdoret commented on tests/test_cff.py
> +    )
**comment(non-blocking):** as the test logic is constant, if you want to make this even neater, you could use pytest fixtures instead to make a parametrized test. See e.g. https://github.com/sdsc-ordes/gimie/blob/1866420f39b15312e6f73cab60c73f8e3ca677d3/tests/test_github.py#L16

2024-11-27 15:14 UTC, cmdoret commented on tests/test_cff.py
> +def test_doi():
```suggestion
def test_parse_doi():
```
**suggestion:** name after action

2024-11-27 15:14 UTC, cmdoret commented on tests/test_cff.py
> +    ).parse(data=cff_file).serialize(format="ttl")
**suggestion(non-blocking):** testing if the DOI is among objects would be more robust than in the serialization, also it lets you check if it's indeed a Literal and not URIRef.

2024-11-27 15:14 UTC, cmdoret commented on tests/test_cff.py
> +    ).parse(data=cff_file).serialize(format="ttl")
prob something like

```py
assert Literal("https://...7") in CffParser(...).parse(...).objects()
```

2024-11-28 12:23 UTC, cmdoret commented
**note:** bumped the dockerfile base layer so that ci succeeds

2024-11-28 13:15 UTC, rmfranken commented on gimie/parsers/cff.py
> +                extracted_cff_triples.add(
That makes total sense - this is much better.

2024-11-28 14:41 UTC, cmdoret approved these changes
LGTM :rocket: well done!

2024-11-28 14:44 UTC, merged