License rework
SDSC-ORD/gimie pull request #68
Opened 2023-09-19 12:57 UTC by rmfranken

Good lord why does it seem impossible to solve this merge conflict. Just trying to draft this pull request here to see if it's resolvable in the Github Web UI because pycharm is causing me to have a stroke.

2023-09-19 13:29 UTC, rmfranken commented
Something is up. I just tried pushing a function rename commit from my local to this branch - and it says it managed - except that commit is nowhere to be found here...
![image](https://github.com/SDSC-ORD/gimie/assets/77491494/bb650db9-40fe-43a4-98da-43a8a0ffa3df)

2023-09-19 13:29 UTC, rmfranken commented
Oh NOW it shows up of course. Ok. I'm going insane ahahah

2023-09-20 11:17 UTC, cmdoret requested changes
Nice, the logic is there and indeed we need to integrate it with the Extractor classes.
Thanks for adding the docstrings and type annotations! I'll work on a separate PR to add a generic `File` object that you could use in your license functions.

2023-09-20 11:17 UTC, cmdoret commented on gimie/sources/common/license.py
> +def github_read_file(url: str, github_token: str = None) -> dict:
If above is implemented,this function will not be needed here (defined as a method of the file object)

2023-09-20 11:17 UTC, cmdoret commented on gimie/sources/common/license.py
> +def github_read_file(url: str, github_token: str = None) -> dict:
headers will then be passed down from the Extractor to the File

2023-09-20 11:17 UTC, cmdoret commented on gimie/sources/common/license.py
> +    return f"https://spdx.org/licenses/{name}.html"
might be overkill to have it as a function if used only once

2023-09-20 11:17 UTC, cmdoret commented on pyproject.toml
> +spdx-lookup = "^0.3.3"
do we still need spdx-lookup and spdx-matcher?

2023-09-20 11:17 UTC, cmdoret commented on gimie/sources/github.py
> +        #         self.license = get_spdx_url(data["licenseInfo"]["spdxId"])
```suggestion

```
I think these could be removed.

2023-09-20 11:17 UTC, cmdoret commented on gimie/sources/github.py
> +        self.license = get_license(repo_url=self.url, headers=self._set_auth())
In the future, `get_license` should take a list of `File` objects. This would allow it to work with Git or Github.

2023-10-10 11:49 UTC, rmfranken commented
Ok, @cmdoret I think I'm ready for your review, only 65 commits later. 🛠️ Hopefully it's the last one!

2023-10-11 09:29 UTC, rmfranken commented on gimie/sources/common/license.py
> +def is_license_path(file: Resource) -> bool:
Understood - that makes more sense indeed.

2023-10-11 09:40 UTC, rmfranken commented on gimie/sources/github.py
> +from scancode.api import get_licenses
Love the term shotgun surgery.

that being said, I see your reasoning - and can get behind it, even with the heavy price of defining dummy functions which I would argue reduce readability.

2023-10-11 09:59 UTC, rmfranken commented on gimie/sources/gitlab.py
> +                license_detections = get_licenses(temp_file.name)[
This was the spiciest one, but I think this works. I was messing around a bit much with the for loop + filling the list of license_id's so I left that in the github+gitlab part, but now the fetching of the license detections and the highest coverage function happen in the generic license.py.

2023-10-12 11:19 UTC, merged