perf(license): tf-idf based matching
SDSC-ORD/gimie pull request #99
Opened 2023-11-13 13:35 UTC by cmdoret

## Context

Up to now, license matching was done using the `scancode-toolkit` package, which has the following drawbacks:

* It depends on compiled packages that are not available on arm64 (i.e. newer macbooks)
* It is slow (2.7 seconds to match an Apache-2.0 license)
* It has many dependencies

## Proposal

This PR aims to replace the rule-based scancode matched with a probabilistic matcher based on TF-IDF.
The matched implementation works as follows:
1. Tokenize input license
2. Compute tf-idf vector
3. Compute cosine similarity against pre-computed tf-idf vectors of all SPDX licenses
4. Pick the license with the highest similarity if it is above a (conservative) similarity threshold

This implies the following:
* We need to ship a matrix of tf-idf vectors and a fitted tf-idf vectorizer with the package, making it a bit heavier
* We need a script to pre-compute these vectors

## Implementation

This PR implements 3 elements:
* A tf-idf vectorizer that can be serialized / parsed to json
* A script to download SPDX licenses and regenerate the pre-computed files.
* A `LicenseParser` which uses this tf-idf vectorizer.

## Alternative solution

Implementing and testing a tf-idf vectorizer might be considered outside the scope of gimie.
The branch `refactor/sklearn-tfidf` implements a variant of this implementation based on the scikit-learn implementation and uses `skops` to securely serialize / parse it (instead of pickle, which has security issues).

Both implementations yield the same results, but the serialized TfidfVectorizer from scikit-learn is much larger and slower to deserialize:

|method|file-size|deserialization time|
|-|-|-|
|custom-tfidf|24kb|0.43ms|
|sklearn+skops|7.8Mb|223ms|
|sklearn+skops+zip-level9|564kb|232ms|

2023-11-22 10:16 UTC, vancauwe requested changes
Really nice :)
I think my main concern is to make our custom class for TFIDF lighter. In sklearn they separate count vectoring from fitting/transforming using tfidf: could we refactor the code to do this too? 
As we are using a custom solution, it would also be ok to keep as is, as we plan to move in the future to using sklearn implementation. The question is also, would the refactoring make a transition easier?

2023-11-22 10:16 UTC, vancauwe commented on gimie/utils/text.py
> +class TfidfVectorizer(BaseModel):
This class is quite big. Is there a reason you didn't follow the split done in sklearn? (CountVectorizer vs TfidfTransformer)  

Count Vectoriser could encompass : 

```python
counts_records: List[Counter[str]] = [
            get_ngram_counts(doc, self.config.ngram_range) for doc in data
        ]
vocab = self.config.vocabulary or self._get_vocabulary(counts_records)
```

2023-11-23 09:11 UTC, cmdoret commented on scripts/generate_tfidf.py
> +#!/usr/bin/env python3
Good point! Let's have a separate issue for this?

2023-11-23 09:19 UTC, cmdoret commented on gimie/parsers/license/__init__.py
> +    data = pkgutil.get_data(__name__, "data/spdx_licenses.csv")
Let's keep it local to the consuming module, following the official [python-packaging guidelines](https://python-packaging.readthedocs.io/en/latest/index.html)

2023-11-23 09:28 UTC, cmdoret commented on gimie/parsers/license/__init__.py
> +# Gimie
Replaced all `__init__.py` to their respective submodule names

2023-11-23 09:38 UTC, cmdoret commented on gimie/parsers/license/__init__.py
> +# Gimie
Indeed, it is not good practice to have entire classes defined in __init__.py.
Let's have a separate issue to refactor those __init__.py files throughout the package.

2023-11-24 12:50 UTC, merged